export const pizzaPricesClasicas =[
    { key: 'Jamón con queso', value: {
        personal: 6500,
        pequeña: 11990,
        mediana: 16990,
        grande: 23990,
      },
      text:"Jamón con queso",
      description:"Tradicional pizza de jamon con queso mozzarela.",
    //   pizzaImg: require('../img/imgMenuPizzas/pizzaQueso.jpg'),
      // pizzaImg: require(''),
    },
    { key: 'Salami', value: {
      personal: 6500,
      pequeña: 11990,
      mediana: 16990,
      grande: 23990,
    },
    text:"Salami",
    description:"Pizza de solo Salami con queso mozzarela.",
    // pizzaImg: require('../img/imgMenuPizzas/pizzaMaiz.png'),
      // pizzaImg: require(''),
    },
    { key: 'Pepperoni', value: {
      personal: 6500,
      pequeña: 11990,
      mediana: 16990,
      grande: 23990,
    },
    text:"Pepperoni",
    description:"Pizza de solo Pepperoni con queso mozzarela.",
    // pizzaImg: require('../img/imgMenuPizzas/pizzaMaiz.png'),
      // pizzaImg: require(''),
    },
    ]
