export const pizzaPricesLigeras =[
    { key: 'Queso', value: {
        personal: 7500,
        pequeña: 12000,
        mediana: 18000,
        grande: 25000,
      },
      text:"Queso",
      description:"Pizza de solo queso, ligera y simple disfrutala.",
      pizzaImg: require('../img/imgMenuPizzas/pizzaQueso.jpg'),
    },
    { key: 'Maiz', value: {
      personal: 8000,
      pequeña: 13000,
      mediana: 20000,
      grande: 27000,
    },
    text:"Maiz",
    description:"Pizza de solo Maiz con queso, ligera, simple y deliciosa.",
    pizzaImg: require('../img/imgMenuPizzas/pizzaMaiz.png'),
    },
    { key: 'Piña', value: {
      personal: 8000,
      pequeña: 13000,
      mediana: 20000,
      grande: 27000,
    },
    text:"Piña",
    description:"Pizza de Piña con queso, ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaPiña.jpg'),
    },
    { key: 'Bocadillo', value: {
      personal: 8000,
      pequeña: 13000,
      mediana: 20000,
      grande: 27000,
    },
    text:"Bocadillo",
    description:"Endulza tu dia con una pizza de Bocadillo con Queso, ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaBocadillo.jpeg'),
    },
    { key: 'Napolitana', value: {
      personal: 8000,
      pequeña: 13000,
      mediana: 20000,
      grande: 27000,
    },
    text:"Napolitana",
    description:"Deliciosa pizza Napolitana (Tomate con Queso), ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaNapolitana.jpg'),
    },
    { key: 'Champiñones', value: {
      personal: 9000,
      pequeña: 14000,
      mediana: 22000,
      grande: 28000,
    },
    text:"Champiñones",
    description:"Deliciosa pizza Champiñones con Queso , ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaChampiñones.jpg'),
    },
    ]
