export const pizzaPricesLigeras =[
    { key: 'Queso', value: {
        personal: 11500,
        pequeña: 15900,
        mediana: 21900,
        grande: 28900,
      },
      text:"Queso",
      description:"Pizza de solo queso, ligera y simple disfrutala.",
      pizzaImg: require('../img/imgMenuPizzas/pizzaQueso.jpg'),
    },
    { key: 'Maiz', value: {
      personal: 11900,
      pequeña: 16900,
      mediana: 23900,
      grande: 30900,
    },
    text:"Maiz",
    description:"Pizza de solo Maiz con queso, ligera, simple y deliciosa.",
    pizzaImg: require('../img/imgMenuPizzas/pizzaMaiz.png'),
    },
    { key: 'Piña', value: {
      personal: 11900,
      pequeña: 16900,
      mediana: 23900,
      grande: 30900,
    },
    text:"Piña",
    description:"Pizza de Piña con queso, ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaPiña.jpg'),
    },
    { key: 'Bocadillo', value: {
      personal: 11900,
      pequeña: 16900,
      mediana: 23900,
      grande: 30900,
    },
    text:"Bocadillo",
    description:"Endulza tu dia con una pizza de Bocadillo con Queso, ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaBocadillo.jpeg'),
    },
    { key: 'Napolitana', value: {
      personal: 11900,
      pequeña: 16900,
      mediana: 23900,
      grande: 30900,
    },
    text:"Napolitana",
    description:"Deliciosa pizza Napolitana (Tomate con Queso), ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaNapolitana.jpg'),
    },
    { key: 'Champiñones', value: {
      personal: 12900,
      pequeña: 17900,
      mediana: 25000,
      grande: 31900,
    },
    text:"Champiñones",
    description:"Deliciosa pizza Champiñones con Queso , ligera, simple y deliciosa.",
    pizzaImg:require('../img/imgMenuPizzas/pizzaChampiñones.jpg'),
    },
    ]
