export const pizzaPricesGourmet =[
  { key: 'Amigazos', value: {
    personal: 16900,
    pequeña: 23900,
    mediana: 30900,
    grande: 36900,
    },
      text:"Amigazos",
      description:"Pizza Amigazos, solo para verdaderos amigos. ( Queso parmesano, en aceite de oliva: pimenton rojo y verde, espinaca, cebolla roja, aceitunas verdes y negras ).",
      pizzaImg:require('../img/imgMenuPizzas/pizzaAmigazos.jpg'),
    },
  { key: 'Amigo secreto', value: {
    personal: 18900,
    pequeña: 25900,
    mediana: 32900,
    grande: 38900,
    },
      text:"Amigo secreto",
      description:"Pizza Amigo secreto, la indicada para mandar la a ese amig@ secreto. ( Tomate en trozos, champiñones, albahaca, queso holandes y parmesano ).",
      pizzaImg:require('../img/imgMenuPizzas/pizzaAmigoSecreto.png'),
    },
    { key: 'Amigos con derecho', value: {
      personal: 18900,
      pequeña: 25900,
      mediana: 32900,
      grande: 38900,
      },
        text:"Amigos con derechos",
        description:"Pizza Amigos con derechos, una pizza para hacer luego de todo. ( Champiñones, tomate cherry, cebolla caramelizada, queso holandes y parmesano ).",
        pizzaImg:require('../img/imgMenuPizzas/pizzaAmigosConDerecho.png'),
      },
  ]
